ignore:
                #  - "path/to/folder"  # ignore folders and all its contents
                #  - "test_*.rb"       # wildcards accepted
                #  - "**/*.py"         # glob accepted
                - "setup.py"